<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <customApplicationComponents>
        <alignment>right</alignment>
        <customApplicationComponent>InteractionLog</customApplicationComponent>
    </customApplicationComponents>
    <defaultLandingTab>standard-home</defaultLandingTab>
    <description>1 stop view for Sales Reps</description>
    <detailPageRefreshMethod>autoRefresh</detailPageRefreshMethod>
    <isServiceCloudConsole>true</isServiceCloudConsole>
    <label>Contact Center Agent Console</label>
    <listPlacement>
        <location>full</location>
    </listPlacement>
    <listRefreshMethod>refreshListRows</listRefreshMethod>
    <tab>standard-Account</tab>
    <tab>standard-Lead</tab>
    <tab>standard-Opportunity</tab>
    <tab>standard-Contact</tab>
    <tab>standard-Dashboard</tab>
    <tab>PPT_Translation__c</tab>
    <tab>Social_Learning</tab>
    <tab>Skill__c</tab>
    <tab>User_Skill__c</tab>
    <tab>AthenaTest__c</tab>
    <tab>HP_PORTAL_URL__c</tab>
    <tab>Promotion__c</tab>
    <tab>Application_Setting__c</tab>
    <tab>Learning_Image__c</tab>
    <tab>Work_Element_Contributor_Role__c</tab>
    <tab>Work_Element_Reviewer_Role__c</tab>
    <tab>Stage_Work_Element_Predecessor__c</tab>
    <tab>Contributor__c</tab>
    <tab>Link__c</tab>
    <tab>Release_Role__c</tab>
    <tab>Release_Deliverable__c</tab>
    <tab>Stage_Work_Element__c</tab>
    <tab>Core_Team_Member__c</tab>
    <tab>Risk__c</tab>
    <tab>Stage_Review__c</tab>
    <tab>CustomObj__c</tab>
    <tab>SLPOLd</tab>
    <tab>Learning_Category__c</tab>
    <tab>Required_Learning_Category__c</tab>
    <tab>ES_User__c</tab>
    <tab>Project__c</tab>
    <tab>sheobj1mar4__c</tab>
    <tab>User_Notification_Subscription__c</tab>
    <tab>Chatter_test__c</tab>
    <tab>Chatter_test_child__c</tab>
    <tab>Root_Cause_Control__c</tab>
    <tab>Business_Impact_Cause__c</tab>
    <tab>Process_Control__c</tab>
    <tab>Root_Cause__c</tab>
    <tab>Business_Impact__c</tab>
    <tab>SLP_Activity</tab>
    <tab>SLP_Process_Onboarding_User__c</tab>
    <tab>SLP_BulkReg_Log__c</tab>
    <tab>SLP_BulkReg__c</tab>
    <tab>UpdateProfileImage</tab>
    <workspaceMappings>
        <mapping>
            <tab>standard-Opportunity</tab>
        </mapping>
        <mapping>
            <tab>sheobj1mar4__c</tab>
        </mapping>
        <mapping>
            <tab>Project__c</tab>
        </mapping>
        <mapping>
            <tab>Business_Impact_Cause__c</tab>
        </mapping>
        <mapping>
            <tab>AthenaTest__c</tab>
        </mapping>
        <mapping>
            <tab>SLP_BulkReg_Log__c</tab>
        </mapping>
        <mapping>
            <tab>ES_User__c</tab>
        </mapping>
        <mapping>
            <tab>Chatter_test__c</tab>
        </mapping>
        <mapping>
            <tab>standard-Contact</tab>
        </mapping>
        <mapping>
            <tab>Core_Team_Member__c</tab>
        </mapping>
        <mapping>
            <tab>Skill__c</tab>
        </mapping>
        <mapping>
            <tab>standard-Dashboard</tab>
        </mapping>
        <mapping>
            <tab>Root_Cause_Control__c</tab>
        </mapping>
        <mapping>
            <tab>Chatter_test_child__c</tab>
        </mapping>
        <mapping>
            <tab>User_Skill__c</tab>
        </mapping>
        <mapping>
            <tab>Business_Impact__c</tab>
        </mapping>
        <mapping>
            <tab>SLPOLd</tab>
        </mapping>
        <mapping>
            <tab>Work_Element_Reviewer_Role__c</tab>
        </mapping>
        <mapping>
            <tab>Process_Control__c</tab>
        </mapping>
        <mapping>
            <tab>CustomObj__c</tab>
        </mapping>
        <mapping>
            <tab>Risk__c</tab>
        </mapping>
        <mapping>
            <tab>Link__c</tab>
        </mapping>
        <mapping>
            <tab>Application_Setting__c</tab>
        </mapping>
        <mapping>
            <tab>Stage_Review__c</tab>
        </mapping>
        <mapping>
            <tab>Stage_Work_Element__c</tab>
        </mapping>
        <mapping>
            <tab>Social_Learning</tab>
        </mapping>
        <mapping>
            <tab>UpdateProfileImage</tab>
        </mapping>
        <mapping>
            <tab>Learning_Category__c</tab>
        </mapping>
        <mapping>
            <tab>PPT_Translation__c</tab>
        </mapping>
        <mapping>
            <tab>Release_Role__c</tab>
        </mapping>
        <mapping>
            <tab>HP_PORTAL_URL__c</tab>
        </mapping>
        <mapping>
            <tab>Learning_Image__c</tab>
        </mapping>
        <mapping>
            <tab>Stage_Work_Element_Predecessor__c</tab>
        </mapping>
        <mapping>
            <tab>Contributor__c</tab>
        </mapping>
        <mapping>
            <tab>SLP_BulkReg__c</tab>
        </mapping>
        <mapping>
            <tab>standard-Lead</tab>
        </mapping>
        <mapping>
            <tab>Required_Learning_Category__c</tab>
        </mapping>
        <mapping>
            <tab>Release_Deliverable__c</tab>
        </mapping>
        <mapping>
            <tab>SLP_Activity</tab>
        </mapping>
        <mapping>
            <tab>Work_Element_Contributor_Role__c</tab>
        </mapping>
        <mapping>
            <tab>SLP_Process_Onboarding_User__c</tab>
        </mapping>
        <mapping>
            <tab>Root_Cause__c</tab>
        </mapping>
        <mapping>
            <tab>Promotion__c</tab>
        </mapping>
        <mapping>
            <tab>standard-Account</tab>
        </mapping>
        <mapping>
            <tab>User_Notification_Subscription__c</tab>
        </mapping>
    </workspaceMappings>
</CustomApplication>
