public class COTestClassUtility{
    public static Boolean ContractAssociateControllerTestVar1 = false;
    public static Boolean ContractAssociateControllerTestVar2 = false;
    public static Boolean ContractAssociateControllerTestVar3 = false;
    public static Boolean ContractExtensionControllerTestVar1 = false;
    public static Boolean ContractExtensionControllerTestVar2 = false;
    public static Boolean ContractExtensionControllerTestVar3 = false;
    public static Boolean ContractExtensionControllerTestVar4 = false;
    public static Boolean RemoveContractAssociationTestVar1 = false;
    public static Boolean OpptyRenewal_SubTypesControllerTestVar1 = false;


}