/*
* NAME : EmployeeBean
* NOTE : This is just data structor to hold Tibco webService Employee ED Hierarchy output data.
* Author : Apttus (Axay Varu)
*/
public class EmployeeBean{
        public String fullName{get;set;}
        public String cn{get;set;}
        public String sn{get;set;}
        public String lastName{get;set;}
        public String givenName{get;set;}
        public String ntUserDomainId{get;set;}
        public String employeeNumber{get;set;}
        public String telephoneNumber{get;set;}
        public String mail{get;set;}
        public String hpPayrollCountryCode{get;set;}
        public String hpLegalName{get;set;}
        public String city{get;set;}
        public String state{get;set;}
        public String postalCode{get;set;}
        public String country{get;set;}
        public String hpSourceCompany{get;set;}
        public String street{get;set;}
        public String manager{get;set;}
        public String hpBusinessGroup{get;set;}
        public String hpBusinessRegion{get;set;}
        public String organisation{get;set;}
        public String hpBusinessUnit{get;set;}
        public String facsimileTelephoneNumber{get;set;}
        public String mobile{get;set;}
        public String hpAdmin{get;set;}
        public String postalAddress{get;set;}
        public String managerEmployeeNumber{get;set;}
        public boolean selected{get;set;}
        public String o{get;set;}  
        public String l{get;set;}         
        public String hpLocationCode{get;set;}
    }