/**********************************************************
* Class Name: OpportunityProductListController
* Author: HP(Mousumi Panda)
* Date: 15-Sept-2012 
* Requirement:Currency subtotal in Oppotunity Currency and Local Currency
* Description: Opportunity Inline VF Page-Products & Services (Related List)
***********************************************************/


public class OpportunityProductListController {
  }