/**********************************************************
* Class Name: SearchAccountMDCPLookUpService 
* Author: HP
* Date: 05-OCT-2012 
* Description: This class does the test coverage for SearchAccountMDCPLookUpService class. 
***********************************************************/

@isTest(SeeAllData=true)
private class SearchAccountMDCPLookUpServiceTest {
private static TestMethod void test1(){ 
SearchAccountMDCPLookUpService oc = new SearchAccountMDCPLookUpService(); 
 new SearchAccountMDCPLookUpService.documents_element (); 
new SearchAccountMDCPLookUpService.organizationAccountSearchResponse_element();
new SearchAccountMDCPLookUpService.accountSearchListInput_element();
new SearchAccountMDCPLookUpService.organizationAccountSearchResult_element();
new SearchAccountMDCPLookUpService.accountSearchList_element();
new SearchAccountMDCPLookUpService.organizationAccountSearchDocuments_element();
new SearchAccountMDCPLookUpService.organizationNonLatinExtendedName_element ();
} 
   
}