@isTest //(SeeAllData=true)
private class soapSforceComSchemasApttusConStubTest {

    private static TestMethod void StubTest(){ 
    soapSforceComSchemasApttusContentStub testStub = new soapSforceComSchemasApttusContentStub(); 

    soapSforceComSchemasApttusContentStub.AgreementWebService agrWS = new soapSforceComSchemasApttusContentStub.AgreementWebService();
    
    soapSforceComSchemasApttusContentStub.SessionHeader_element  sessionHdr = new soapSforceComSchemasApttusContentStub.SessionHeader_element(); 
 soapSforceComSchemasApttusContentStub.publishToContentRepository_element pubAgreement = new soapSforceComSchemasApttusContentStub.publishToContentRepository_element();
 soapSforceComSchemasApttusContentStub.CallOptions_element callOptions = new soapSforceComSchemasApttusContentStub.CallOptions_element();
 soapSforceComSchemasApttusContentStub.DebuggingInfo_element  debugInfo = new soapSforceComSchemasApttusContentStub.DebuggingInfo_element();
 soapSforceComSchemasApttusContentStub.AllowFieldTruncationHeader_element  fieldTruncation = new soapSforceComSchemasApttusContentStub.AllowFieldTruncationHeader_element ();
 soapSforceComSchemasApttusContentStub.LogInfo  logInfo = new soapSforceComSchemasApttusContentStub.LogInfo();
 soapSforceComSchemasApttusContentStub.DebuggingHeader_element debugHeader = new soapSforceComSchemasApttusContentStub.DebuggingHeader_element();
 soapSforceComSchemasApttusContentStub.publishToContentRepositoryResponse_element   publishResponse = new soapSforceComSchemasApttusContentStub.publishToContentRepositoryResponse_element();
    }    

}