<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
<SOAP-ENV:Body>
<ns0:EDResponse xmlns:ns0="http://www.tibco.com/schemas/EDInterface/BusinessUseCases/SharedResources/Schemas/EDOutPut">
<ns0:Message>test user1 || 12345678 || test1@apttus.com || 52525523</ns0:Message>
<ns0:Message>test user2 || 52525523 || test2@apttus.com || 87654321</ns0:Message>
<ns0:Message>test user3 || 25256632 || test3@apttus.com || 52525523</ns0:Message>
</ns0:EDResponse>
</SOAP-ENV:Body>
</SOAP-ENV:Envelope>